# Generated by Django 5.0.6 on 2024-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('book_code', models.IntegerField()),
                ('author_name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=128)),
                ('amount', models.IntegerField()),
                ('available_books', models.IntegerField()),
                ('created_date', models.DateField()),
                ('created_by', models.IntegerField()),
                ('updated_date', models.DateField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('book_img', models.FileField(upload_to='image')),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
